---
  - name: Install basic packages
    yum: name={{ item.name }} enablerepo=epel state=latest
    become: yes
    with_items:
      - "{{ basic_packages }}"

  - name: Install build essentials
    yum: name={{ item.name }} enablerepo=epel state=latest
    become: yes
    with_items:
      - "{{ build_packages }}"

  - name: Check tmux already installed
    register: tmux_installed
    failed_when: tmux_installed.rc not in [0, 1]
    changed_when: False
    shell: which tmux && tmux -V | grep {{ tmux_version }}

  - name: Build and Install tmux
    when: tmux_installed.rc == 1
    shell: |
      git clone {{ tmux_repository }} /tmp/tmux
      cd /tmp/tmux
      git checkout {{ tmux_version }}
      sh autogen.sh >/dev/null
      ./configure >/dev/null
      make >/dev/null
      sudo make install

  - name: Get latest peco version
    changed_when: False
    register: peco_latest_version
    shell: curl -sI https://github.com/peco/peco/releases/latest | awk -F'/' '/^Location:/{print $NF}'

  - name: Download latest peco
    changed_when: False
    get_url:
      url: https://github.com/peco/peco/releases/download/{{ peco_latest_version.stdout }}/peco_linux_amd64.tar.gz
      dest: /tmp/peco_linux_amd64.tar.gz

  - name: Extract peco
    unarchive: src=/tmp/peco_linux_amd64.tar.gz dest=/tmp/

  - name: Install /usr/local/bin/peco
    become: true
    copy: src=/tmp/peco_linux_amd64/peco dest=/usr/local/bin/ mode=0755
