---
  - name: Install basic packages
    yum: name={{ item.name }} enablerepo=epel state=latest
    become: yes
    with_items:
      - "{{ basic_packages }}"

  - name: Install build essentials
    yum: name={{ item.name }} enablerepo=epel state=latest
    become: yes
    with_items:
      - "{{ build_packages }}"
