---
  - name: Include tasks
    include_tasks: '{{ include_yml }}'
    loop_control:
      loop_var: include_yml
    with_first_found:
      - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_os_family }}.yml'
        skip: false
