[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/echodoc.vim'
hook_add = 'source ~/.config/nvim/plugins/echodoc.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive', 'vim-gitgutter']
hook_add = 'source ~/.config/nvim/plugins/airline.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline-themes']
hook_add = 'source ~/.config/nvim/plugins/airlinethemes.rc.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = 'source ~/.config/nvim/plugins/neoterm.rc.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source ~/.config/nvim/plugins/indentline.rc.vim'

[[plugins]]  # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
hook_add = 'source ~/.config/nvim/plugins/vim-precious.rc.vim'

[[plugins]]  # カーソル位置のコンテキストのftを判定する
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'aliev/vim-compiler-python'

[[plugins]]
repo = 'janko-m/vim-test'
depends = ['vim-dispatch']
hook_add = 'source ~/.config/nvim/plugins/vim-test.rc.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
hook_add = 'source ~/.config/nvim/plugins/fzf.rc.vim'

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = 'source ~/.config/nvim/plugins/openbrowser.rc.vim'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source ~/.config/nvim/plugins/vim-easymotion.rc.vim'

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = 'source ~/.config/nvim/plugins/vim-lsp.rc.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = 'source ~/.config/nvim/plugins/vim-lsp-settings.rc.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = 'source ~/.config/nvim/plugins/asyncomplete.rc.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = 'source ~/.config/nvim/plugins/ultisnips.rc.vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-ultisnips.vim'
hook_add = 'source ~/.config/nvim/plugins/asyncomplete-ultisnips.rc.vim'

[[plugins]]
repo = 'yami-beta/asyncomplete-omni.vim'
hook_add = 'source ~/.config/nvim/plugins/asyncomplete-omni.rc.vim'

#[[plugins]]
#repo = 'thomasfaingnaert/vim-lsp-snippets'

#[[plugins]]
#repo = 'thomasfaingnaert/vim-lsp-ultisnips'

#[[plugins]]
#repo = 'hrsh7th/vim-vsnip'
#hook_add = 'source ~/.config/nvim/plugins/vim-vsnip.rc.vim'

#[[plugins]]
#repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'source ~/.config/nvim/plugins/defx.rc.vim'
