# name             lazyOff lazyOn timing
# ----------------+-------+------+------
# hook_add         o       o      プラグインが dein.vim によって追加されたとき
# hook_source      x       o      プラグインが読み込まれる直前
# hook_post_source x       o      プラグインが読み込まれた直後
# hook_post_update o       o      プラグインが更新された直後

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_cmd = 'Qfreplace'

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_source = 'source ~/.config/nvim/plugins/jedi.rc.vim'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'scrooloose/nerdcommenter'
on_map = '<Plug>NERDCommenterToggle'
hook_add = 'source ~/.config/nvim/plugins/nerdcommenter.rc.vim'

[[plugins]]
repo = 'glidenote/memolist.vim'
on_func = ['MemoNew', 'MemoList', 'MemoGrep']
hook_add = 'source ~/.config/nvim/plugins/memolist.rc.vim'

[[plugins]]
repo = 'gregsexton/gitv'
depends = ['vim-fugitive']
on_func = 'Gitv'
hook_source = 'source ~/.config/nvim/plugins/gitv.rc.vim'

[[plugins]]
repo = 'vim-scripts/gtags.vim'
on_func = 'GtagsCursor'
hook_source = 'source ~/.config/nvim/plugins/gtags.rc.vim'

[[plugins]]
repo = 'majutsushi/tagbar'
on_func = ['TagbarToggle']
hook_add = 'source ~/.config/nvim/plugins/tagbar.rc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
on_func = ['Unite']
hook_source = 'source ~/.config/nvim/plugins/unite.rc.vim'

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = 'ansible'

[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = ['vim-operator-user', 'vim-repeat']
on_map = '<Plug>'
hook_add = 'source ~/.config/nvim/plugins/vim-operator-surround.rc.vim'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 't9md/vim-quickhl'
on_map = '<Plug>'
hook_add = 'source ~/.config/nvim/plugins/quickhl.rc.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'
hook_add = 'source ~/.config/nvim/plugins/quickrun.rc.vim'

[[plugins]]
repo = 'justinhoward/fzf-neoyank'
depends = ['neoyank.vim', 'fzf.vim']
on_func = ['FZFNeoyank', 'FZFNeoyankSelection']
hook_add = 'source ~/.config/nvim/plugins/fzf-neoyank.rc.vim'

[[plugins]]
repo = 'uarun/vim-protobuf'
on_ft = 'proto'

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'
