---
extensions:
  - { name: atlassian.atlascode }
  - { name: auchenberg.vscode-browser-preview }
  - { name: donjayamanne.githistory }
  - { name: dracula-theme.theme-dracula }
  - { name: eamodio.gitlens }
  - { name: formulahendry.code-runner }
  - { name: humao.rest-client }
  - { name: jebbs.plantuml }
  - { name: lehni.vscode-titlebar-less-macos }
  - { name: ms-python.python }
  - { name: ms-vscode.cpptools }
  - { name: ms-vscode.Go }
  - { name: msjsdiag.debugger-for-chrome }
  - { name: redhat.vscode-yaml }
  - { name: ryu1kn.edit-with-shell }
  - { name: sgryjp.japanese-word-handler }
  - { name: slevesque.perforce }
  - { name: vscode-icons-team.vscode-icons }
  - { name: vscodevim.vim }
