---
build_packages:
  - { name: epel-release }
  - { name: gcc }
  - { name: gcc-c++ }
  - { name: patch }
  - { name: readline-devel }
  - { name: zlib-devel }
  - { name: gmp }
  - { name: gmp-devel }
  - { name: tk-devel }
  - { name: tcl-devel }
  - { name: sqlite-devel }
  - { name: bzip2-devel }
  - { name: openssl-devel }
  - { name: libxml2-devel }
  - { name: libxslt-devel }
  - { name: cmake }
  - { name: libtool }
  - { name: autoconf }
  - { name: automake }
  - { name: pkgconfig }
  - { name: ncurses-devel }
  - { name: libevent-devel }
  - { name: libffi-devel }
build_libs:
  - { name: libreadline-dev }
  - { name: libbz2-dev }
  - { name: libsqlite3-dev }
  - { name: libssl-dev }
  - { name: zlib1g-dev }
  - { name: wget }
  - { name: curl }
  - { name: llvm }
  - { name: libncurses5-dev }
  - { name: libncursesw5-dev }
  - { name: xz-utils }
  - { name: tk-dev }
  - { name: libffi-dev }
  - { name: liblzma-dev }
  - { name: python-openssl }
