---
tmux_repository: https://github.com/tmux/tmux.git
tmux_version: 2.3

homebrew_taps:
  - { tap: homebrew/cask }
  - { tap: homebrew/cask-fonts }
  - { tap: sanemat/font }

homebrew_cask_packages:
  - { name: xquartz }
  - { name: font-ricty-diminished }
  #- { name: font-source-code-pro-for-powerline }
  #- { name: iterm2 }
  #- { name: google-japanese-ime }

homebrew_packages:
  - { name: autoconf }
  - { name: automake }
  - { name: pkg-config }
  - { name: fontforge }
  #- { name: ricty, install_options: [with-powerline] }
  - { name: git }
  - { name: zsh }
  - { name: ripgrep }
  - { name: jq }

basic_packages:
  - { name: epel-release }
  - { name: git }
  - { name: zsh }
  - { name: ripgrep }
  - { name: the_silver_searcher }
  - { name: global-ctags }
  - { name: global }
  - { name: xorg-x11-xauth }
  - { name: xsel }
  - { name: jq }
  - { name: rlwrap }

build_packages:
  - { name: gcc }
  - { name: gcc-c++ }
  - { name: patch }
  - { name: readline-devel }
  - { name: zlib-devel }
  - { name: gmp }
  - { name: gmp-devel }
  - { name: tk-devel }
  - { name: tcl-devel }
  - { name: sqlite-devel }
  - { name: bzip2-devel }
  - { name: openssl-devel }
  - { name: libxml2-devel }
  - { name: libxslt-devel }
  - { name: cmake }
  - { name: libtool }
  - { name: autoconf }
  - { name: automake }
  - { name: pkgconfig }
  - { name: ncurses-devel }
  - { name: libevent-devel }
  - { name: clang }

pip_packages:
  - { name: pip }
  - { name: flake8 }
  - { name: awscli }
