---
tmux_repository: https://github.com/tmux/tmux.git
tmux_version: 2.3

basic_packages:
  - { name: epel-release }
  - { name: git }
  - { name: zsh }
  - { name: the_silver_searcher }
  - { name: global-ctags }
  - { name: global }
  - { name: xorg-x11-xauth }
  - { name: xsel }
  - { name: jq }

build_packages:
  - { name: gcc }
  - { name: gcc-c++ }
  - { name: patch }
  - { name: readline-devel }
  - { name: zlib-devel }
  - { name: gmp }
  - { name: gmp-devel }
  - { name: tk-devel }
  - { name: tcl-devel }
  - { name: sqlite-devel }
  - { name: bzip2-devel }
  - { name: openssl-devel }
  - { name: libxml2-devel }
  - { name: libxslt-devel }
  - { name: cmake }
  - { name: libtool }
  - { name: autoconf }
  - { name: automake }
  - { name: pkgconfig }
  - { name: ncurses-devel }
  - { name: libevent-devel }
  - { name: clang }
