---
tmux_repository: https://github.com/tmux/tmux.git
tmux_version: 2.3

homebrew_taps:
  - { tap: homebrew/cask }
  - { tap: homebrew/cask-fonts }
  - { tap: sanemat/font }

homebrew_cask_packages:
  - { name: xquartz }
  - { name: font-ricty-diminished }
  #- { name: font-source-code-pro-for-powerline }
  - { name: iterm2 }
  - { name: google-japanese-ime }
  - { name: karabiner-elements }
  - { name: docker }
  #- { name: google-chrome }
  #- { name: visual-code-studio }
  #- { name: google-cloud-sdk }
  #- { name: virtualbox }
  #- { name: virtualbox-extension-pack }
  - { name: slack }

homebrew_packages:
  - { name: readline }
  #- { name: openssl, state: linked, install_options: [force, with-openssl] }
  - { name: openssl, install_options: [force, with-openssl] }
  - { name: autoconf }
  - { name: automake }
  - { name: pkg-config }
  - { name: fontforge }
  #- { name: ricty, install_options: [with-powerline] }
  - { name: git }
  - { name: zsh }
  #- { name: rust }
  #- { name: ripgrep }
  - { name: global }
  - { name: jq }
  - { name: ghq }
  - { name: wget }
  - { name: curl }
  - { name: ctags }
  - { name: tmux }
  - { name: packer }
  - { name: docker-completion }
  - { name: docker-compose-completion }
  #- { name: plantuml }
  - { name: libffi }
  - { name: sqlite }
  - { name: gettext }
  - { name: gnupg }
  - { name: bat }

basic_packages:
  - { name: epel-release }
  #- { name: git }
  #- { name: zsh }
  - { name: ripgrep }
  #- { name: the_silver_searcher }
  #- { name: global-ctags }
  #- { name: global }
  #- { name: xorg-x11-xauth }
  #- { name: xsel }
  #- { name: jq }
  #- { name: rlwrap }

build_packages:
  - { name: epel-release }
  - { name: gcc }
  - { name: gcc-c++ }
  - { name: patch }
  - { name: readline-devel }
  - { name: zlib-devel }
  - { name: gmp }
  - { name: gmp-devel }
  - { name: tk-devel }
  - { name: tcl-devel }
  - { name: sqlite-devel }
  - { name: bzip2-devel }
  - { name: openssl-devel }
  - { name: libxml2-devel }
  - { name: libxslt-devel }
  - { name: cmake }
  - { name: libtool }
  - { name: autoconf }
  - { name: automake }
  - { name: pkgconfig }
  - { name: ncurses-devel }
  - { name: libevent-devel }
  - { name: clang }
  - { name: libffi-devel }

pip_packages:
  - { name: pip }
  - { name: flake8 }
  - { name: awscli }

osx_defaults:
  - domain: org.macosforge.xquartz.X11
    key: app_to_run
    type: string
    value: ""

  # 自動大文字の無効化
  - domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false

  # トラックパッド
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: DragLock
    type: int
    value: 0

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Dragging
    type: int
    value: 0

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadCornerSecondaryClick
    type: int
    value: 0

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadFiveFingerPinchGesture
    type: int
    value: 2

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadFourFingerHorizSwipeGesture
    type: int
    value: 2

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadFourFingerPinchGesture
    type: int
    value: 2

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadFourFingerVertSwipeGesture
    type: int
    value: 2

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadHandResting
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadHorizScroll
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadMomentumScroll
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadPinch
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRightClick
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadRotate
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadScroll
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadThreeFingerDrag
    type: int
    value: 0

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadThreeFingerHorizSwipeGesture
    type: int
    value: 2

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadThreeFingerTapGesture
    type: int
    value: 0

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadThreeFingerVertSwipeGesture
    type: int
    value: 2

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadTwoFingerDoubleTapGesture
    type: int
    value: 1

  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadTwoFingerFromRightEdgeSwipeGesture
    type: int
    value: 3

  # Dockの位置
  - domain: com.apple.dock
    key: orientation
    type: string
    value: "bottom"

  # Dockを自動的に隠す
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: false

  # Dockのズーム
  - domain: com.apple.dock
    key: magnification
    type: bool
    value: true

  # Dockのアイコンサイズ
  - domain: com.apple.dock
    key: tilesize
    type: float
    value: 27

  # すべての拡張子のファイルを表示
  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    notify: "Restart Finder"

  # 隠しファイルを表示する
  - domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    notify: "Restart Finder"

  # パスバーを表示
  - domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: true
    notify: "Restart Finder"

  # .DS_Storeを作らない
  - domain: com.apple.finder
    key: DSDontWriteNetworkStores
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.finder
    key: DSDontWriteUSBStores
    type: bool
    value: true
    notify: "Restart Finder"
