---
- name: Install Development Tools
  yum:
    name: "@Development tools"
    state: present
  become: yes

- name: Install Dependencies
  yum:
    name: [ curl, file, git ]
    enablerepo: epel
    state: latest
  become: yes

- name: Create Linuxbrew bin directory
  file:
    path: ~/.linuxbrew/bin
    recurse: yes

- name: Install Linuxbrew
  git:
    repo: https://github.com/Homebrew/brew.git
    dest: ~/.linuxbrew/Homebrew

- name: Link Linuxbrew
  file:
    path: ~/.linuxbrew/bin/brew
    src: ../Homebrew/bin/brew
    state: link

- name: Setup Linuxbrew
  blockinfile:
    create: yes
    path: ~/.bash_profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK linuxbrew"
    block: |
      eval $(~/.linuxbrew/bin/brew shellenv)
      #export LD_LIBRARY_PATH="$(brew --prefix)/lib:$LD_LIBRARY_PATH"
