[settings]
install_before = "7d"
pin = true

[tools]
aws-vault = "latest"
awscli = "2.27.49"
gcloud = "latest"
gh = "latest"
go = "1.25.0"
nodejs = "23.7.0"
python = "3.12.0"
sops = "3.11.0"
terraform = "1.13.4"
terragrunt = "0.83.0"
usage = "latest"
kubectl = "latest"
npm = "11.11.1"
"npm:@github/copilot" = "1.0.21"
"npm:difit" = "4.0.1"
"github:k1LoW/mo" = "1.0.0"
