[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/echodoc.vim'
hook_add = 'source ~/.config/nvim/plugins/echodoc.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['tagbar', 'vim-fugitive', 'vim-gitgutter']
hook_add = 'source ~/.config/nvim/plugins/airline.rc.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline-themes']
hook_add = 'source ~/.config/nvim/plugins/airlinethemes.rc.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = 'source ~/.config/nvim/plugins/neoterm.rc.vim'

[[plugins]]
repo = 'neomake/neomake'
hook_add = 'source ~/.config/nvim/plugins/neomake.rc.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source ~/.config/nvim/plugins/indentline.rc.vim'

[[plugins]]  # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
hook_add = 'source ~/.config/nvim/plugins/vim-precious.rc.vim'

[[plugins]]  # カーソル位置のコンテキストのftを判定する
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'aliev/vim-compiler-python'

[[plugins]]
repo = 'janko-m/vim-test'
depends = ['vim-dispatch']
hook_add = '''
let g:test#strategy = 'dispatch'
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = 'source ~/.config/nvim/plugins/openbrowser.rc.vim'
