---
- name: local develop environment
  hosts: 'local'
  #gather_facts: no
  become: no
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  vars:
    HOME: "{{ lookup('env', 'HOME') }}"
    CACHE: "{{ HOME }}/.cache/ansible"
  roles:
    - { role: base, tags: [ base ] }
    - { role: common, tags: [ common ] }
    - { role: envs, tags: [ envs ] }
    - { role: vscode, tags: [ never, vscode ] }
