;; % curl -fsSkL https://raw.github.com/cask/cask/master/go | python
;; % cask init
;; % cask
;; % cask update
;; (require 'cask "~/.cask/cask.el")
;; (cask-initialize)

(source gnu)
(source melpa)
(source marmalade)

;; autocomplete
(depends-on "auto-complete")
(depends-on "ac-dabbrev")

;; package
(depends-on "auto-install")
(depends-on "pallet")

;; edit
(depends-on "auto-async-byte-compile")
(depends-on "goto-chg")
(depends-on "browse-kill-ring")
(depends-on "migemo" :git "https://github.com/emacs-jp/migemo.git")
(depends-on "open-junk-file")
(depends-on "point-undo")
(depends-on "popwin")
(depends-on "recentf-ext")
(depends-on "revive")
(depends-on "sequential-command")

;; colortheme
(depends-on "color-theme")
(depends-on "color-theme-solarized")
(depends-on "color-theme-molokai")
(depends-on "powerline")

(depends-on "elscreen" :git "https://github.com/knu/elscreen.git")
(depends-on "flycheck")
(depends-on "pbcopy")
(depends-on "popup")
(depends-on "quickrun")
(depends-on "session")

;; grep
(depends-on "grep-a-lot")
(depends-on "color-moccur")
(depends-on "ag")
(depends-on "wgrep-ag")

;; helm
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "ac-helm")
(depends-on "helm-c-moccur")
(depends-on "helm-c-yasnippet")
(depends-on "helm-descbinds")
(depends-on "helm-gist")
(depends-on "helm-git-grep")
(depends-on "helm-google")
(depends-on "helm-gtags")
(depends-on "helm-helm-commands")
(depends-on "helm-migemo")
(depends-on "helm-pydoc")
(depends-on "helm-rb")

;; git
(depends-on "magit")
(depends-on "gist" :git "https://github.com/defunkt/gist.el")
(depends-on "git-gutter")

;; org
(depends-on "org")

;; markdown
(depends-on "markdown-mode")

;; javascript
(depends-on "js2-mode")
(depends-on "json-mode")

;; ruby
(depends-on "rhtml-mode")
(depends-on "ruby-mode")
(depends-on "ruby-block")
(depends-on "ruby-electric")
(depends-on "ruby-end")
